export const KNUST_DEPARTMENTS = [
  "Academic Affairs",
  "Accra Office",
  "Basic Schools",
  "Development Office",
  "Environment and Sanitation",
  "Estate Organisation",
  "Finance Office",
  "Fire Management",
  "Health Services",
  "Human Resource Development",
  "Information Technology Services",
  "Institute of Distance Learning",
  "Legal Services",
  "Municipal Services",
  "Obuasi Campus Administration",
  "Office of Grants and Research",
  "Procurement Office",
  "Quality Assurance and Planning",
  "School of Graduate Studies",
  "Security Services",
  "Student Affairs",
  "Transport Department",
  "University Hospital",
  "University Library",
  "University Printing Press",
  "University Relations",
  "Vice-Chancellor's Office",
  "Works and Physical Development",
] as const;

export const ASSIGNABLE_DEPARTMENTS = [
  "Environment and Sanitation",
  "Estate Organisation",
  "Fire Management",
  "Health Services",
  "Information Technology Services",
  "Municipal Services",
  "Security Services",
  "Student Affairs",
  "Transport Department",
  "Works and Physical Development",
  "Other",
] as const;
